services:
  db:
    image: postgres:14
    container_name: provider_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: provider_db
    ports:
      - "5051:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - provider_network
  app:
    build:
      context: .
    container_name: provider_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/provider_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresql
    volumes:
      - ./logs:/app/logs
    networks:
      - provider_network
volumes:
  pgdata:

networks:
  provider_network:
